config/routes.rb
Rails.application.routes.draw do
  
  get 'feed' => 'user#feed'
  get 'signup' => 'user#new'
  get 'index' => 'user#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'service_agreement' => 'static_pages#serviceAgreement'
  get 'contact' => 'static_pages#contact'

  #Gets users based on profile number
  get 'user/:id' => 'user#show'

  resources :schedule_event
  #resources :group
  get 'group' => 'group#index'
  #match 'user/:firstN', to: 'user#show', via: [:get, :post], :constrain => { :username => /[a-zA-Z-]+/ }
  
  resources :user do 
    member do
      get :following, :followers
    end
  end

  
  get 'schedule/:id' => 'user#schedule'
  #resources :schedule_event, only: [:create, :edit, :update, :destroy]
  resources :relationships,       only: [:create, :destroy]
  root 'static_pages#home'
end

app/controllers/schedule_event_controller.rb
class ScheduleEventController < ApplicationController
	#before_action :logged_in_user, only: [:show]
	#before_action :correct_user, only: [:show]

	def create
		user = current_user
		@event = current_user.events.create(event_params)
		if @event.save
			flash[:notice] = "Your event was created successfully."
			#redirect_to root_url
			redirect_to(:controller =>'user', :action => 'show', id: user.id)
		else
			flash[:error] = "There was a problem creating your event. Please check everything is correct."
			redirect_to(:controller =>'user', :action => 'show', id: user.id)
		end
	end

	def edit
		@user = current_user
		@event = Event.find(params[:id])
		if (@user.id != @event.user.id)
			redirect_to(root_url)
		end
	end

	def show		
    	@event = Event.find(params[:id]) if logged_in?
    	@user = User.find(@event.user_id) if logged_in?
    	#@user = User.find(params[:user_id])
  	end

	def update
		@event = Event.find(params[:id])
		if @event.update(event_update_params)
			flash[:notice] = "Your event has been updated successfully"
			redirect_to url_for(:controller => :schedule_event, :action => :show)
		else
			flash[:error] = "There was a problem updating your event."
			render 'edit'
		end
	end

	def delete
    	@event = Event.find(params[:id])
    	@event.destroy
	end

	def destroy
		@user = current_user
	    event = Event.find(params[:id])
	    event.destroy
	    flash[:notice] = "Event was deleted"
	    redirect_to(:controller =>'user', :action => 'show', id: @user.id)
	end
	

	private
		def event_params
			params.require(:event).permit(:title, :description, :date_of_event, :time_of_event)
		end

		def event_update_params
			params.require(:event).permit(:title, :description)
		end

    	# def correct_user
	    #   @user = current_user
	    #   @event = Event.find(params[:id])
	    #   redirect_to(root_url) unless(@user.id == @event.user.id)
	    # end
end

app/helpers/schedule_event_helper.rb
module ScheduleEventHelper
end

app/views/schedule_event/edit.html.erb
<h1 align="center">Edit Event</h1>
<li align="center" style="text-align: center; color:red; list-style-type: none;"><% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: 'name' %>
<% end %></li>

	<ul style="list-style-type: none;">
	    <%= form_for @event, :url => {:action => "update"} do |f| %>

	    	<li><%= f.label :title, "Title: " %>
	      <%= f.text_field :title %></li>

	      	<li><%= f.label :description, "Description: " %>
	      <%= f.text_field :description, style: 'width: 20%; height:10%;' %></li>

	      	<li><%= f.submit "Save changes" %></li>
	    <% end %>
	</ul>

app/views/schedule_event/show.html.erb
<h1 align="center">Event</h1>
<% if logged_in? %>
	<div align="center">
		<h3><%= @event.title.capitalize + " created by: " + @user.firstN %>.</h3><h3><%= "Event was created " + @event.created_at.strftime("%b %e, %Y at %l:%M:%S %p") %></h3>
		<h4>The event should last about  + " and " + </h4>
		<h4>People invited to this event: </h4>
		<% if current_user.id == @event.user.id %>
			<%= link_to("Edit Event", controller: "schedule_event", action:"edit") %>|
      		<%= link_to "Delete", schedule_event_path(@event), :confirm => "Are you sure?", :method => :delete %>
      	<% end %>
	</div>
<% else %>
	<div align="center">Please <%= link_to("Login", controller: "sessions", action: "new") %> to see event</div>
<% end %>