config/routes.rb
Rails.application.routes.draw do
  
  get 'feed' => 'user#feed'
  get 'signup' => 'user#new'
  get 'index' => 'user#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'service_agreement' => 'static_pages#serviceAgreement'
  get 'contact' => 'static_pages#contact'

  #Gets users based on profile number
  get 'user/:id' => 'user#show'

  resources :schedule_event
  #resources :group
  get 'group' => 'group#index'
  #match 'user/:firstN', to: 'user#show', via: [:get, :post], :constrain => { :username => /[a-zA-Z-]+/ }
  
  resources :user do 
    member do
      get :following, :followers
    end
  end

  
  get 'schedule/:id' => 'user#schedule'
  #resources :schedule_event, only: [:create, :edit, :update, :destroy]
  resources :relationships,       only: [:create, :destroy]
  root 'static_pages#home'
end

app/views/layouts/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
	  <%= f.submit "Unfollow" %>
	<% end %>
  <% else %>
    <%= form_for(current_user.active_relationships.build) do |f| %>
	  <div><%= hidden_field_tag :followed_id, @user.id %></div>
	  <%= f.submit "Follow" %>
	<% end %>
  <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<style>
footer.foot{
	position: relative;
    margin-top: 50px;
    padding-top: 20px;
    padding-bottom: 40px;
    font-size: 12px;
    line-height: 1.5;
    color: #100;
    border-top: 1px solid #fff;
}
ul#menu {
	text-align: center;
    list-style-type: none;
    margin: 0px auto;
    padding: 0px;
}
ul#menu li {
    display:inline;
}
</style>

<footer class="foot">
	<div align="center">Calendar30</div>
	<div class="header"> 
		<ul id="menu" align="center">
			<li><%= link_to("Help", controller: "static_pages", action: "help")%></li><li> </li>
			<li><%= link_to("About", controller: "static_pages", action: "about")%></li><li> </li>
		  	<li><%= link_to("Contact", controller: "static_pages", action: "contact")%></li>
		</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<style>
ul#menu li {
    display:inline;
}
div.abs_left {
	position: absolute;
	top: 10px;
	left: 15px;
	font-size: 14px;
}
div.abs_right{
	position: absolute;
	top: 10px;
	right: 15px;
}
.header a:link, a:visited{
	color:white;
	background-color: #0600AB;
	padding-left: .5em;
	padding-right: .5em;
	border-radius: 5px;
}
.header a:hover{
	color:#75FFA8;
}
.header a:active{
	color:white;
}
</style>

	<div class="abs_left">
		<ul id="menu" class="header">
			<li><%= link_to("Home", controller: "static_pages", action:"home") %></li><li> </li>
			<li><%= link_to("Feed", controller: "user", action:"feed") %></li><li> </li>
			<li><%= link_to("Groups", controller: "group", action:"index")%> <!-- , controller: "group", action:"index"-->
		</ul>
	</div>
	<div class="abs_right header">
		<ul id="menu">
			<% if logged_in? == false %>
				<%= form_for(:session, url: login_path) do |f| %>
						<table>
							<li style="font-size: 10px;"><%= f.text_field :email, placeholder: "Email", :size=>"12", class: 'form-control', style: 'border-radius: 3px' %> </li>
							<li style="font-size: 10px"><%= f.password_field :password, placeholder: "Password", :size=>"10", style: 'border-radius: 3px' %></li>
					      	<li><%= f.label :remember_me, class: "checkbox inline" do %></li>
							<li><%= f.check_box :remember_me %></li>
							<li style="font-size:12px">Remember me </li>
					      <% end %>
							<li colspan="2"><%= f.submit "Log in" %></li>
				<% end %>
			  				<li style="font-size:14px"> <%= link_to("Sign up", controller: "user", action: "new")%></li>
			  			</table>
		  	<% else %>
		  			<table class="header">
		  				<li style="font-size:14px"><%= link_to("Schedule", controller:"user", action:"index", id: @current_user.id) %></li><li> </li>
		  				<%= link_to(current_user) do %>
		  					<li style="font-size:14px"><%= current_user.firstN.capitalize %> </li>
		  				<% end %>
		  				</li><li> </li>
		  				<li style="font-size:14px"><%= link_to("Log out", logout_path, method: "delete")%></li>
		  			</table>
		  	<% end %>
		</ul>
	</div>

app/views/layouts/_schedule.html.erb
<!-- 
	HTML Schedule Here.
-->
<style>
	.schedule_tiptext {
	}
	.schedule_description {
		display:none;
		position:absolute;
		border: 2px solid #454545; 
		color: white; 
		background-color: #555AF0; 
		z-index: 1;
		overflow: auto;
		border-radius: 5px;
	}
	.schedule_create_event{
		border: 2px solid black;
		border-radius:10px; 
		padding:1px; 
		background-color:#FFB871;
		height: 10%;
	}
	#schedule_top-left{
		width:48%; height:38%;
		top:18%; left:8%; 
	}
	#schedule_bot-left{
		width:48%; height:38%;
		bottom:20%; left:8%;   
	}
	#schedule_right{ 
		width:24%; height:60%; 
		right:8%; top:20%;"
	}
</style>
<!--
	Need to be able to create an event with people.
-->

<table width="100%" style="background-color:#BFE0FF; table-layout:fixed">
	<colgroup>
		<col width="20%" />
		<col width="20%" />
		<col width="20%" />
		<col width="20%" />
		<col width="20%" />
	</colgroup>
	<% dateArray = Array.new %>
	<% for i in 0..5 %>
		<tr>
			<% for j in 0..4 %>
				<% calendarDate = Time.now + ((i*5) + j).day.to_i %>
				<% wdayValue = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>
				<% monthValue = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October","November", "December"] %>
				<% dateArray.insert((i*5) + j, calendarDate.strftime("%m-%d-%y")) %>
				<td style="height:60px; border:2px solid #474747; color:#353535; border-radius:8px; max-width: 200px; overflow: hidden; white-space: nowrap; background-color:#72B9FF;">
					<div class="schedule_tiptext">
						<% if ((calendarDate.day == Time.now.day) && (calendarDate.month == Time.now.month)) %>
							<div style="color:#72FFB9;">
						<% else %>
							<div>
						<% end %>
								<%= wdayValue[calendarDate.wday] %>, <%= monthValue[calendarDate.month-1] %> <%= calendarDate.day %>:
							</div>
						<table>
							<tr><td>Events:</td>
								<td>
									<% @feed_items.each do |event| %>
										<% if event.date_of_event.to_s == calendarDate.strftime("%Y-%m-%d") %>
											<b><%=event.title%></b>
										<% end %>
									<% end %>
								</td>
							<!--
								^
								Show the events for the day by calling a request to the database for events on the day.
								The events should be added based on the "calendarDate" variable.
								something like... 

								calendarValue.getEventsForToday()
							-->
							</tr>
							<tr><td>Availibility</td></tr>
							<!--
								^
								This should only show a status from green to red based on how busy other people are compared to you.
							-->
						</table>

						<div class="schedule_description" 
							<% if (j < 3) && (i < 4) %>
								id="schedule_top-left"
							<% elsif (i >= 4) && (j <= 2) %>
								id="schedule_bot-left"
							<% else %>
								id="schedule_right"
							<% end %>
						>
							<div style="margin-left: 15px; margin-top:10px; font-size:16px; padding:none;">Description for Events of <%= wdayValue[calendarDate.wday] + " " + calendarDate.strftime("%m-%d") %>:
						</div>
							<% @feed_items.each do |event| %>
								<% if event.date_of_event.to_s == calendarDate.strftime("%Y-%m-%d") %>
									<%= link_to controller: "schedule_event", action: "show", id: event.id do %>
										<div style="padding-left:25px; font-size:12px; color:white;" class="event_information">
											<%= event.time_of_event.strftime("%l:%M %p") + ": " + event.title + " created by: " + event.user.username %> 
										</div>
									<% end %>
								<% end %>
							<% end %>
						</div>
					</div>
				</td>
			<% end %>
		</tr>
	<% end %>
</table>

<br>
<!--
	Create events down here. \/
-->
<div align="center" class="schedule_create_event"
	<% if flash[:notice] %>
		style="background-color:#B8FF71;"
	<% elsif flash[:error] %>
		style="background-color:#FF7172;"
	<% end %>
>
	<% if logged_in? %>
		<%= form_for(@event, :url => { :controller => "schedule_event", :action => "create" }) do |f| %>
			<div><span style="font-size:12px"><b>Time of event:</b></span><%= f.time_select :time_of_event, {ampm: true},  style:'width:8%; valign:50%' %><span style="font-size:12px"><b> Date of Event: </b></span><%= f.date_field :date_of_event, style:'width:10%; valign:50%; align:center;' %></div>
			<div><%= f.text_field :title, placeholder:"Name of Event", style:'width:10%; top:50%; vertical-align:middle;' %> <%= f.text_field :description, placeholder:"Small Description Here", style:'width:15%; top:50%; vertical-align:middle;' %><%= f.submit "Add Event", style:'width:8%; top:50%; vertical-align:middle;' %> </div>
		<% end %>
	<% else %>
		<h3>Please sign in to create an event</h3>
	<% end %>
	<% flash.each do |key, value| %>
  		<%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>
</div>
<!--
	End of creating an event
-->

<script type="text/javascript">
	$(".schedule_tiptext").click(function() {
	    $(this).children("div.schedule_description").show();
	}).mouseleave(function() {
	    $(this).children("div.schedule_description").hide();
	});

	$(".schedule_tiptext").mouseleave(function() {
		$("div.event_information").children("div.jquery_show_full_description").hide();
	});
	
</script>

app/views/layouts/_stats.html.erb
<style>
.stats {
  overflow: auto;
  margin-top: 0;
  padding: 0;
  a {
    float: left;
    padding: 0 10px;
    border-left: 1px solid $gray-lighter;
    color: gray;
    &:first-child {
      padding-left: 0;
      border: 0;
    }
    &:hover {
      text-decoration: none;
      color: blue;
    }
  }
  strong {
    display: block;
  }
}
</style>

<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Calendar30</title>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>